---
title: "Pharmacy First"
output:
  html_document:
  theme: journal
date: "01-01-2020 through 31-06-2024 by month"
---

```{css, echo=FALSE}
pre {
  max-height: 300px;
  overflow-y: auto;
}
pre[class] {
  max-height: 200px;
}
```

```{=html}
<style>
  body {
    text-align: justify;
     font-size: 11pt}
</style>
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

$~$

## Background <a name="background"></a>

Add background here.

$~$

## Methods <a name="methods"></a>

This study used data from OpenSAFELY-TPP, which covers 40% of the population of England. For a description of the representativeness of this sample, please see our manuscript [here](https://wellcomeopenresearch.org/articles/7-191/v1). Individuals were included if they were alive and registered at a TPP practice each month, across the study period. Patients were excluded if their listed age was not between 0 and 120 years.

Counts represent patients with at least one clinical code of relevance in that month. Patients with more than one of the same clinical code in a month were only counted once. Rates divide the count by the included study population and multiply by 1,000 to achieve a rate per 1,000 registered patients.

Counts \<=7 have been redacted and all numbers rounded to the nearest 5 to avoid potential re-identification of individuals. The rates displayed were computed with these rounded counts.

Our data relies on relevant SNOMED CT codes being added to a patient's GP record to indicate a consultation under the Pharmacy First service and any treatments provided. To support transfer of community pharmacy consultation summary data into a patients primary care electronic health record he Pharmacy First service specification on [GP Connect: Update Record](https://digital.nhs.uk/services/gp-connect/gp-connect-in-your-organisation/gp-connect-update-record) to update a patient's GP record with consultation information from the community pharmacy. Following the launch of the Pharmacy First service, there has been a [gradual roll-out of GP Connect: Update Record](https://cpe.org.uk/our-news/gp-connect-update-record-rollout-and-flow-of-information/) across the approved community pharmacy IT system suppliers.

*Need to complete this*

Links to the codelist for each analysis can be found beneath the relevant section.

This report contains the following sections:

-   [Clinical Pathways](#pathways)
    -   [SNOMED CT codes](#pathwayssnomedcodes)
    -   [Clinical condition](#condition)
    -   [Days of the week](#dotw)
    -   [NHS region](#region)
    -   [Ethnicity](#ethnicity)
    -   [IMD](#imd)
    -   [Shingles](#shingles)
        -   [Sex](#shingles_sex)
        -   [Age](#shingles_age)
        -   [Ethnicity](#shingles_ethnicity)
        -   [IMD](#shingles_imd)
        -   [Region](#shingles_region)
        -   [Medication supply](#shingles_supply)
    -   [Urinary tract infection etc.](#urt)

$~$

## Clinical Pathways <a name="pathways"></a>

This report focuses on the Clinical Pathways element of that Pharmacy First service.

### SNOMED CT codes <a name="pathwayssnomedcodes"></a>

Add text here about the SNOMED CT codes in use. Community Pharmacist (CP) Consultation Service for minor illness - entered via the Update Record system Pharmacy First service - manually coding

> LINE CHATT - NATIONAL COUNTS OF THE 2 SNOMED CT codes - Community Pharmacist (CP) Consultation Service for minor illness (procedure): "1577041000000109" and Pharmacy First service (qualifier value): "983341000000102"

### Clinical Condition <a name="condition"></a>

This section focuses on the clinical conditions within the Clinical Pathways element of that Pharmacy First service:

#### Counts by clinical condition

Here we show the number of consultations for each of the Pharmacy First Clinical Pathways Clinical Conditions

> LINE CHART WITH COUNT OF EACH CLINICAL CONDITION

### Counts by day of the week <a name="dotw"></a>

Here we show the number of consultations for the Pharmacy First Clinical Pathways by day of the week the consultation was conducted. (Mainly of interest to show what happens at weekends etc e.g. when GP practices are closed).

> BAR CHART WITH COUNT BY DAY OF THE WEEK

### Rates by region <a name="region"></a>

Here we show the rates of consultations for the Pharmacy First Clinical Pathways by the NHS Region in which the patient is registered. (Might not be the region where PF consultation conducted).

> RATES OF ANY PF CLINICAL (either of Community Pharmacist (CP) Consultation Service for minor illness (procedure): "1577041000000109" and Pharmacy First service (qualifier value): "983341000000102") PATHWAY BY REGION

### Rates by ethnicity <a name="ethnicity"></a>

Here we show the rates of consultations for the Pharmacy First Clinical Pathways by patient ethnicity

> RATES OF ANY PF CLINICAL PATHWAY BY ETHNICITY

### Rates by IMD <a name="imd"></a>

Here we show the rates of consultations for the Pharmacy First Clinical Pathways by IMD (based on patient address)

> RATES OF ANY PF CLINICAL PATHWAY BY IMD

# ---- BELOW HERE FOR FUTURE VERSIONS ----

### Shingles <a name="shingles"></a> {#shingles}

Here we show the rates specifically for consultations conducted under the Shingles clinical pathway:

#### Rates by sex <a name="shingles_sex"></a>

Here we show the rates of consultations for the Pharmacy First Shingles Clinical Pathways by sex

> RATES OF SHINGLES CLINICAL PATHWAY BY SEX

#### Rates by age <a name="shingles_age"></a>

Here we show the rates of consultations for the Pharmacy First Shingles Clinical Pathways by age. (Would need to consider age bands as different for each pathway)

> RATES OF SHINGLES CLINICAL PATHWAY BY AGE

#### Rates by ethnicity <a name="shingles_ethnicity"></a>

Here we show the rates of consultations for the Pharmacy First Shingles Clinical Pathways by ethnicity

> RATES OF SHINGLES CLINICAL PATHWAY BY ETHNICITY

#### Rates by IMD <a name="shingles_imd"></a>

Here we show the rates of consultations for the Pharmacy First Shingles Clinical Pathways by IMD

> RATES OF SHINGLES CLINICAL PATHWAY BY IMD

#### Rates by region <a name="shingles_region"></a>

Here we show the rates of consultations for the Pharmacy First Shingles Clinical Pathways by NHS region

> RATES OF SHINGLES CLINICAL PATHWAY BY REGION

#### Rates by medication supply <a name="shingles_supply"></a>

Here we show the percentage of consultations for the Pharmacy First Shingles Clinical Pathways with vs without medication supply. (Could also potentially show details of which medication issued)

> BAR PLOT OF PERCENTAGE OF SHINGLES CLINICAL PATHWAY WITH/WITHOUT MEDICATION SUPPLIED

### Urinary tract infection etc. <a name="urt"></a>

> *placeholder*
