version: '3.0'

# Ignore this`expectation` block. It is required but not used, and will be removed in future versions.
expectations:
  population_size: 1000

actions:

  generate_dataset_definition_table1:
    run: >
      ehrql:v1
       generate-dataset analysis/dataset_definition_table1.py
       --test-data-file analysis/test_dataset_definition_table1.py
       --output output/population/pf_table1.csv.gz
    outputs:
      highly_sensitive:
        cohort: output/population/pf_table1.csv.gz

  create_table1:
    run: r:latest analysis/create_tables.R
    needs: [generate_dataset_definition_table1]
    outputs:
      moderately_sensitive:
        dataset: output/population/pf_demographics.csv

  generate_pf_breakdown_measures:
    run: >
      ehrql:v1 generate-measures analysis/measures_definition_pf_breakdown.py
      --output output/measures/pf_breakdown_measures.csv
    outputs:
      moderately_sensitive:
        measure: output/measures/pf_breakdown_measures.csv

  generate_pf_condition_provider_measures:
    run: >
      ehrql:v1 generate-measures analysis/measures_definition_pf_condition_provider.py
      --output output/measures/pf_condition_provider_measures.csv
    outputs:
      moderately_sensitive:
        measure: output/measures/pf_condition_provider_measures.csv

  generate_pf_medications_measures:
    run: >
      ehrql:v1 generate-measures analysis/measures_definition_pf_medications.py
      --dummy-tables dummy_tables
      --output output/measures/pf_medications_measures.csv
    outputs:
      moderately_sensitive:
        measure: output/measures/pf_medications_measures.csv

  generate_pf_statistics_measures:
    run: >
      ehrql:v1 generate-measures analysis/measures_definition_pf_descriptive_stats.py
      --dummy-tables dummy_tables
      --output output/measures/pf_descriptive_stats_measures.csv
    outputs:
      moderately_sensitive:
        measure: output/measures/pf_descriptive_stats_measures.csv

  generate_pf_med_counts_measures:
    run: >
      ehrql:v1 generate-measures analysis/measures_definition_pf_consultation_med_counts.py
      --dummy-tables dummy_tables
      --output output/measures/consultation_med_counts_measures.csv
    outputs:
      moderately_sensitive:
        measure: output/measures/consultation_med_counts_measures.csv

  tidy_med_measures:
    run: r:latest analysis/tidy_measures_med_counts.R
    needs: [generate_pf_medications_measures, generate_pf_med_counts_measures]
    outputs:
      moderately_sensitive:
        measure_pf_meds: output/measures/pf_medications_measures_tidy.csv 
        measure_consult_meds: output/measures/consultation_med_counts_measures_tidy.csv
  
  generate_pf_opensafely_report:
    run: >
      r:v2 -e 'rmarkdown::render(
        "reports/pharmacy_first_report.Rmd",
        knit_root_dir = "/workspace",
        output_dir = "/workspace/output/report"
      )'
    outputs:
      moderately_sensitive:
        html: output/report/pharmacy_first_report.html  