version: "3.0"

# Ignore this`expectation` block. It is required but not used, and will be removed in future versions.
expectations:
  population_size: 1000

actions:
  generate_dataset_definition_tables:
    run: >
      ehrql:v1
       generate-dataset analysis/dataset_definition_tables.py
       --test-data-file analysis/test_dataset_definition_tables.py
       --dummy-data-file dummy_data/pf_tables_dataset.csv
       --output output/population/pf_tables.csv.gz
    outputs:
      highly_sensitive:
        cohort: output/population/pf_tables.csv.gz

  create_tables:
    run: r:v2 analysis/create_tables.R
    needs: [generate_dataset_definition_tables]
    outputs:
      moderately_sensitive:
        dataset: output/population/pf_tables.csv

  generate_pf_statistics_measures:
    run: >
      ehrql:v1 generate-measures analysis/measures_definition_pf_descriptive_stats.py
      --dummy-tables dummy_tables
      --output output/measures/pf_descriptive_stats_measures.csv
    outputs:
      moderately_sensitive:
        measure: output/measures/pf_descriptive_stats_measures.csv

  generate_pf_breakdown_measures:
    run: >
      ehrql:v1 generate-measures analysis/measures_definition_pf_breakdown.py
      --output output/measures/pf_breakdown_measures.csv
    outputs:
      moderately_sensitive:
        measure: output/measures/pf_breakdown_measures.csv

  generate_pf_med_counts_measures:
    run: >
      ehrql:v1 generate-measures analysis/measures_definition_pf_med_counts.py
      --dummy-tables dummy_tables
      --output output/measures/pf_medications_measures.csv
    outputs:
      moderately_sensitive:
        measure: output/measures/pf_medications_measures.csv

  tidy_med_measures:
    run: r:latest analysis/tidy_measures_med_counts.R
    needs: [generate_pf_med_counts_measures]
    outputs:
      moderately_sensitive:
        measure_pf_meds: output/measures/pf_medications_measures_tidy.csv

  generate_pf_opensafely_report:
    run: >
      r:v2 -e 'rmarkdown::render(
        "reports/pharmacy_first_report.Rmd",
        knit_root_dir = "/workspace",
        output_dir = "/workspace/output/report"
      )'
    needs:
      - generate_dataset_definition_tables
      - create_tables
      - generate_pf_statistics_measures
      - generate_pf_breakdown_measures
      - generate_pf_med_counts_measures
      - tidy_med_measures
    outputs:
      moderately_sensitive:
        html: output/report/pharmacy_first_report.html
        pf_demographics: output/report/data/df_demographics_table.csv
        pf_breakdowns: output/report/data/df_measures.csv
        pf_clinical_conditions: output/report/data/df_clinical_pathways_by_sex.csv
        pf_med_counts: output/report/data/df_pf_and_non_pf_med_counts.csv
        pf_consultations: output/report/data/df_pf_consultations.csv
        pf_descriptive_stats: output/report/data/df_pf_descriptive_stats.csv
        pf_counts: output/report/figures/figure1.png
        pf_by_sex: output/report/figures/figure2sex.png
        pf_by_age: output/report/figures/figure3age.png
        pf_by_imd: output/report/figures/figure4imd.png
        pf_by_region: output/report/figures/figure5region.png
        pf_by_ethnicity: output/report/figures/figure6ethnicity.png
        pf_completeness: output/report/figures/figure7.png

  generate_pf_opensafely_monthly_report:
    run: >
      r:v2 -e 'rmarkdown::render(
        "reports/pharmacy_first_monthly_report.Rmd",
        knit_root_dir = "/workspace",
        output_dir = "/workspace/output/report"
      )'
    needs:
      - create_tables
      - generate_pf_statistics_measures
      - generate_pf_breakdown_measures
      - generate_pf_med_counts_measures
      - tidy_med_measures
    outputs:
      moderately_sensitive:
        html: output/report/pharmacy_first_monthly_report.html
        pf_breakdowns: output/report/data/df_measures_updated.csv
        pf_med_counts: output/report/data/df_pf_and_non_pf_med_counts_updated.csv
        pf_consultations: output/report/data/df_pf_consultations_updated.csv
        pf_descriptive_stats: output/report/data/df_pf_descriptive_stats_updated.csv
        pf_counts: output/report/figures/figure1_updated.png
        pf_by_sex: output/report/figures/figure2sex_updated.png
        pf_by_age: output/report/figures/figure3age_updated.png
        pf_by_imd: output/report/figures/figure4imd_updated.png
        pf_by_region: output/report/figures/figure5region_updated.png
        pf_by_ethnicity: output/report/figures/figure6ethnicity_updated.png
        pf_completeness: output/report/figures/figure7_updated.png
        pf_clinical_conditions: output/report/figures/figure8clinicalpathways_updated.png