version: '3.0'

# Ignore this`expectation` block. It is required but not used, and will be removed in future versions.
expectations:
  population_size: 1000

actions:
  generate_pf_measures:
    run: >
      ehrql:v1 generate-measures analysis/measures_definition_pf_codes_conditions.py
      --output output/measures/pf_codes_conditions_measures.csv
    outputs:
      moderately_sensitive:
        measure: output/measures/pf_codes_conditions_measures.csv
  
  generate_pf_report:
    run: >
      r:latest -e 'rmarkdown::render("reports/pharmacy_first_report.Rmd", output_dir = "/workspace/output/reports", knit_root_dir = "/workspace")'
    needs: [generate_pf_measures]
    outputs:
      moderately_sensitive:
        report: output/reports/pharmacy_first_report.html

  generate_pf_dataset_definition:
    run: >
      ehrql:v1
       generate-dataset analysis/pf_dataset_definition.py
       --test-data-file analysis/test_pf_dataset_definition.py
       --output output/population/pf_population.csv.gz
    outputs:
      highly_sensitive:
        cohort: output/population/pf_population.csv.gz