version: '3.0'

# Ignore this`expectation` block. It is required but not used, and will be removed in future versions.
expectations:
  population_size: 1000

actions:
  generate_pf_breakdown_measures:
    run: >
      ehrql:v1 generate-measures analysis/measures_definition_pf_breakdown.py
      --output output/measures/pf_breakdown_measures.csv
    outputs:
      moderately_sensitive:
        measure: output/measures/pf_breakdown_measures.csv

  generate_pf_condition_provider_measures:
    run: >
      ehrql:v1 generate-measures analysis/measures_definition_pf_condition_provider.py
      --output output/measures/pf_condition_provider_measures.csv
    outputs:
      moderately_sensitive:
        measure: output/measures/pf_condition_provider_measures.csv

  generate_pf_medications_measures:
    run: >
      ehrql:v1 generate-measures analysis/measures_definition_pf_medications.py
      --dummy-tables dummy_tables
      --output output/measures/pf_medications_measures.csv
    outputs:
      moderately_sensitive:
        measure: output/measures/pf_medications_measures.csv

  generate_pf_statistics_measures:
    run: >
      ehrql:v1 generate-measures analysis/measures_definition_pf_descriptive_stats.py
      --dummy-tables dummy_tables
      --output output/measures/pf_descriptive_stats_measures.csv
    outputs:
      moderately_sensitive:
        measure: output/measures/pf_descriptive_stats_measures.csv

  generate_pf_dataset_definition:
    run: >
      ehrql:v1
       generate-dataset analysis/pf_dataset_definition.py
       --test-data-file analysis/test_pf_dataset_definition.py
       --output output/population/pf_population.csv.gz
    outputs:
      highly_sensitive:
        cohort: output/population/pf_population.csv.gz

  generate_pf_med_counts_measures:
    run: >
      ehrql:v1 generate-measures analysis/measures_definition_pf_consultation_med_counts.py
      --dummy-tables dummy_tables
      --output output/measures/consultation_med_counts_measures.csv
    outputs:
      moderately_sensitive:
        measure: output/measures/consultation_med_counts_measures.csv

  pf_demographics_table:
    run: r:latest analysis/dataset_definition_tables.R
    needs: [generate_pf_dataset_definition]
    outputs:
      moderately_sensitive:
        dataset: output/population/pf_demographics.csv