version: '3.0'

# Ignore this`expectation` block. It is required but not used, and will be removed in future versions.
expectations:
  population_size: 1000

actions:
  generate_pf_consultation_measures:
    run: >
      ehrql:v1 generate-measures analysis/measures_definition_pf_codes_conditions.py
      --output output/measures/pf_codes_conditions_measures.csv
    outputs:
      moderately_sensitive:
        measure: output/measures/pf_codes_conditions_measures.csv

  generate_seasonality_consultation_measures:
    run: >
      ehrql:v1 generate-measures analysis/measures_definition_seasonality_conditions.py
      --output output/measures/seasonality_conditions_measures.csv
    outputs:
      moderately_sensitive:
        measure: output/measures/seasonality_conditions_measures.csv

  generate_pf_medication_measures:
    run: >
      ehrql:v1 generate-measures analysis/measures_definition_pf_medications.py
      --dummy-tables dummy_tables
      --output output/measures/pf_medications_measures.csv
    outputs:
      moderately_sensitive:
        measure: output/measures/pf_medications_measures.csv

  generate_pf_dataset_definition:
    run: >
      ehrql:v1
       generate-dataset analysis/pf_dataset_definition.py
       --test-data-file analysis/test_pf_dataset_definition.py
       --output output/population/pf_population.csv.gz
    outputs:
      highly_sensitive:
        cohort: output/population/pf_population.csv.gz