version: '3.0'

# Ignore this`expectation` block. It is required but not used, and will be removed in future versions.
expectations:
  population_size: 1000

actions:

  generate_dataset_definition_tables:
    run: >
      ehrql:v1
       generate-dataset analysis/dataset_definition_tables.py
       --test-data-file analysis/test_dataset_definition_tables.py
       --dummy-data-file dummy_data/pf_tables_dataset.csv
       --output output/population/pf_tables_dataset.csv.gz
    outputs:
      highly_sensitive:
        cohort: output/population/pf_tables_dataset.csv.gz

  create_tables:
    run: r:v2 analysis/create_tables.R
    needs: [generate_dataset_definition_tables]
    outputs:
      moderately_sensitive:
        dataset: output/population/pf_tables.csv

  generate_pf_statistics_measures:
    run: >
      ehrql:v1 generate-measures analysis/measures_definition_pf_descriptive_stats.py
      --dummy-tables dummy_tables
      --output output/measures/pf_descriptive_stats_measures.csv
    outputs:
      moderately_sensitive:
        measure: output/measures/pf_descriptive_stats_measures.csv

  generate_pf_breakdown_measures:
    run: >
      ehrql:v1 generate-measures analysis/measures_definition_pf_breakdown.py
      --output output/measures/pf_breakdown_measures.csv
    outputs:
      moderately_sensitive:
        measure: output/measures/pf_breakdown_measures.csv

  generate_pf_med_counts_measures:
    run: >
      ehrql:v1 generate-measures analysis/measures_definition_pf_med_counts.py
      --dummy-tables dummy_tables
      --output output/measures/pf_medications_measures.csv
    outputs:
      moderately_sensitive:
        measure: output/measures/pf_medications_measures.csv

  tidy_med_measures:
    run: r:latest analysis/tidy_measures_med_counts.R
    needs: [generate_pf_med_counts_measures]
    outputs:
      moderately_sensitive:
        measure_pf_meds: output/measures/pf_medications_measures_tidy.csv 

  # We dont need this one at the moment so commenting out 
  # generate_pf_condition_provider_measures:
  #   run: >
  #     ehrql:v1 generate-measures analysis/measures_definition_pf_condition_provider.py
  #     --output output/measures/pf_condition_provider_measures.csv
  #   outputs:
  #     moderately_sensitive:
  #       measure: output/measures/pf_condition_provider_measures.csv

  # We need to fix the dummy data for the tests to complete for this action 
  # generate_pf_opensafely_report:
  #   run: >
  #     r:v2 -e 'rmarkdown::render(
  #       "reports/pharmacy_first_report.Rmd",
  #       knit_root_dir = "/workspace",
  #       output_dir = "/workspace/output/report"
  #     )'
  #   needs:
  #     - generate_pf_breakdown_measures
  #     - generate_pf_medications_measures
  #     - generate_pf_statistics_measures
  #     - generate_pf_med_counts_measures
  #     - tidy_med_measures
  #   outputs:
  #     moderately_sensitive:
  #       html: output/report/pharmacy_first_report.html  