version: '3.0'

# Ignore this`expectation` block. It is required but not used, and will be removed in future versions.
expectations:
  population_size: 1000

actions:
  generate_pf_measures:
    run: >
      ehrql:v1 generate-measures analysis/report_measures.py
      --output output/report/conditions_measures.csv
    outputs:
      moderately_sensitive:
        measure: output/report/conditions_measures.csv  