```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(here)
library(readr)
library(gt)
library(patchwork)
```

```{r echo=FALSE, message=FALSE}
source(here("lib", "functions", "create_tables.R"))

# Load functions
source(here("lib", "functions", "tidy_measures.R"))
source(here("lib", "functions", "plot_measures.R"))

# Load validation data:
# - df_bsa_medication_validation: date, pharmacy_advanced_service, bnf_paragraph, count
# - df_bsa_consultation_validation: date, consultation_type, source, count_method, count
source(here("lib", "functions", "load_validation_data.R"))

# Load opensafely ouputs:
# - df_measures: measure, interval_start, interval_end, ratio numerator, denominator, age_band, sex,imd, region, ethnicity
# - df_descriptive_stats: measure, interval_start, interval_end, ratio numerator, denominator
# - df_pfmed: measure, interval_start, interval_end, ratio, numerator, denominator, dmd_code
# - df_condition_provider: measure, interval_start, interval_end, ratio, numerator, denominator, pf_status, imd
source(here("lib", "functions", "load_opensafely_outputs.R"))
```

```{r echo=FALSE, message=FALSE}
# Create clinical pathways table
tab_clinical_pathways <- create_clinical_pathways_table("Table 1. Pharmacy First population criteria")
gtsave(tab_clinical_pathways, filename = here("released_output", "results", "tables", "tab_pf_condition_criteria.png"))
```

```{r echo=FALSE}
# Create pharmacy first service codes dataframe
tab_pf_service_codes <- create_pf_service_codes_table("Table 2. Pharmacy First consultation codes")
gtsave(tab_pf_service_codes, filename = here("released_output", "results", "tables", "tab_pf_service_codelist.png"))
```

```{r echo=FALSE, message=FALSE}
tab_pf_condition_codes <- create_clinical_conditions_codes_table("Table 3. Pharmacy First condition codes")
gtsave(tab_pf_condition_codes, filename = here("released_output", "results", "tables", "tab_pf_condition_codes.png"))
```

## Table 1

```{r, message=FALSE, warning=FALSE}
population_table_demo <- population_table %>% 
  pivot_wider(names_from = "population", values_from = "value")

if (nrow(population_table_demo) < 136) {
  print("Table 1 cannot be generated with current dummy data")
} else if (nrow(population_table_demo) == 136) {
  df_demographics_table <- population_table_demo %>%
  filter(table == "tab_demographics") %>%
  pivot_wider(names_from = metric, values_from = c(pharmacy_first, tpp)) %>%
  select(-table) %>%
  mutate(category = factor(category,
    levels = c("sex", "age_band", "ethnicity", "imd", "region"),
    labels = c("Sex", "Age Band", "Ethnicity", "IMD", "Region")
  )) %>%
  mutate(
    subcategory = recode(subcategory,
    "female" = "Female",
    "male" = "Male",
    "Other South Asian" = "Any other Asian background",
    "Other Black" = "Any other Black background",
    "Other Mixed" = "Any other mixed background",
    "All other ethnic groups" = "Any other ethnic group",
    "Other White" = "Any other White background")) |>
  mutate(order = c(1:23, 28, 36, 24, 29, 35, 25, 40, 30, 34, 27, 39, 26, 37, 38, 32, 31, 33)) |> 
  arrange(order) |>
  select(-order)

demographics_table <- gt_demographics(df_demographics_table)
}

gtsave(demographics_table, here("released_output", "results", "manuscript", "table1.png"))
```

## Table 2

```{r, message=FALSE, warning=FALSE}
population_table <- population_table %>%
  filter(population == "pharmacy_first")

if (nrow(population_table) < 136) {
  print("Table cannot be generated with current dummy data")
} else if (nrow(population_table) == 136) {
df_clinical_pathways_by_sex <- population_table %>%
  filter(table == "tab_pf_pathways_by_sex") %>%
  pivot_wider(names_from = metric, values_from = value) %>%
  select(-table) %>%
  pivot_wider(names_from = category, values_from = numerator) %>%
  group_by(subcategory) %>%
  mutate(total = female + male) %>%
  ungroup() %>%
  mutate(
    pct = total / sum(total),
    subcategory = factor(subcategory,
      levels = c(
        "otitismedia",
        "impetigo",
        "insectbite",
        "shingles",
        "sinusitis",
        "sorethroat",
        "uti"
      ),
      labels = c(
        "Acute otitis media",
        "Impetigo",
        "Infected insect bites",
        "Shingles",
        "Sinusitis",
        "Sore throat",
        "Uncomplicated UTI"
      )
    )
  ) %>% 
  arrange(subcategory) %>% 
  select(-population)

clinical_pathways_by_sex <- gt_pathways(df_clinical_pathways_by_sex)
}

gtsave(clinical_pathways_by_sex, here("released_output", "results", "manuscript", "table2.png"))
```

## Table 3

```{r, message=FALSE, warning=FALSE, echo = FALSE}
df_consultation_med_counts <- read_csv(
  here("released_output", "measures", "pf_medications_measures_tidy.csv"),
  col_types = cols(dmd_code = col_character())
)

# VMP lookup was taken from the dmd tables held in BigQuery
# This lookup table will need to be updated periodically if new VMPs appear in the data
# To find SQL code for this query, please refer to Chris's comment in PR #144 ("Update VMP mapping")

vmp_lookup <- read_csv(
  here("lib", "reference", "vmp_vtm_lookup.csv"),
  col_types = cols(id = col_character())
) %>%
  rename(code = id)

# Total number of medication linked to a PF consultation
med_counts <- df_consultation_med_counts %>%
  summarise(total = sum(numerator))

codelist_file_names <- list.files(
  here("codelists"),
  pattern = "\\.csv$",
  full.names = FALSE
)

top10_nonpf_med_code_desc <- tribble(
  ~code, ~term,
  "37388111000001102", "Macrobid 100mg modified-release capsules",
  "531611000001106", "Difflam 0.15% spray",
  "3697711000001104", "EarCalm 2% spray",
  "42533911000001101", "Coryen 27.5micrograms/dose nasal spray",
  "623911000001105", "Hydrocortisone 1% cream",
  "4530711000001104", "Covonia Sore Throat 0.2%/0.05% oromucosal spray menthol",
  "42100111000001106", "Benzydamine 0.15% oromucosal spray sugar free",
  "29311000001104", "Piriton 2mg/5ml syrup",
  "17290311000001107", "Benzydamine 0.15% oromucosal spray sugar free",
  "4648111000001108", "Robitussin Chesty Cough 100mg/5ml oral solution"
)

combined_med_code_desc <- vmp_lookup |>
  dplyr::bind_rows(top10_nonpf_med_code_desc)

df_pf_med_counts <- df_consultation_med_counts |>
  select(numerator, code = dmd_code, pharmacy_first_med) |>
  left_join(combined_med_code_desc, by = "code") |>
  filter(numerator > 0) |>
  select(-code) %>%
  group_by(pharmacy_first_med, vmp_nm) |>
  summarise(count = sum(numerator, na.rm = TRUE)) |>
  filter(!is.na(vmp_nm)) %>%
  ungroup() |>
  group_by(pharmacy_first_med) |>
  mutate(ratio_by_group = count / sum(count, na.na.rm = TRUE)) |>
  slice_max(order_by = ratio_by_group, n = 10) |>
  ungroup()

# %>%
# filter(pharmacy_first_med == TRUE) %>%
# summarise(total = sum(count))

df_pf_and_non_pf_med_counts <- df_pf_med_counts %>%
  arrange(!pharmacy_first_med) %>%
  mutate(pharmacy_first_med = factor(pharmacy_first_med,
    levels = c(FALSE, TRUE),
    labels = c(("Medication not included in codelists"), "Medication included in codelists")
  )) %>%
  group_by(pharmacy_first_med)

gt_top_meds(df_pf_and_non_pf_med_counts)

gtsave(
  tab_pf_med_counts,
  here("released_output", "results", "tables", "tab_pf_med_counts.png"),
)
```