---
title: "Pharmacy First Manuscript Results"
output:
  html_document:
    toc: true
    toc_depth: 4
  pdf_document: default
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(here)
library(readr)
library(gt)
library(patchwork)
library(scales)
library(paletteer)
```

```{r load-data, message=FALSE, warning=FALSE}
# Load functions
source(here("lib", "functions", "tidy_measures.R"))
source(here("lib", "functions", "plot_measures.R"))

# Load validation data:
# - df_bsa_medication_validation: date, pharmacy_advanced_service, bnf_paragraph, count
# - df_bsa_consultation_validation: date, consultation_type, source, count_method, count
source(here("lib", "functions", "load_validation_data.R"))

# Load opensafely ouputs:
# - df_measures: measure, interval_start, interval_end, ratio numerator, denominator, age_band, sex,imd, region, ethnicity
# - df_descriptive_stats: measure, interval_start, interval_end, ratio numerator, denominator
# - df_pfmed: measure, interval_start, interval_end, ratio, numerator, denominator, dmd_code
# - df_condition_provider: measure, interval_start, interval_end, ratio, numerator, denominator, pf_status, imd
source(here("lib", "functions", "load_opensafely_outputs.R"))
```

# Results

## OpenSAFELY total counts

### Figure 1

```{r, message=FALSE, warning=FALSE}
# Create figure for total count of Pharmacy First consultations for each code (3 codes)
df_pf_consultations <- df_measures |>
  filter(measure_desc == "clinical_service") |>
  filter(is.na(group_by)) |>
  select(measure, interval_start, numerator) |>
  mutate(measure = factor(measure,
    levels = c(
      "Consultation Service",
      "Pharmacy First Consultation",
      "Community Pharmacy First Service"
    ),
    labels = c(
      "CP Consultation Service for minor illness (1577041000000109)",
      "Pharmacy First service (983341000000102)",
      "CP Pharmacy First Service (2129921000000100)"
    )
  )) |>
  group_by(interval_start) |>
  mutate(
    pf_consultation_total = sum(numerator, na.rm = TRUE),
    data_desc = "Pharmacy First Consultation"
  ) |>
  rename(pf_code = measure) |>
  filter(interval_start >= "2024-02-01") |>
  ungroup() |>
  pivot_longer(
    cols = c(numerator, pf_consultation_total),
    names_to = "measure"
  ) |>
  mutate(
    measure = case_when(
      measure == "pf_consultation_total" ~ "Pharmacy First Service Total",
      measure == "numerator" ~ pf_code
    ),
    data_desc = case_when(
      measure == "Pharmacy First Service Total" ~ "total",
      measure %in% c(
        "CP Consultation Service for minor illness (1577041000000109)",
        "Pharmacy First service (983341000000102)",
        "CP Pharmacy First Service (2129921000000100)"
      ) ~ "breakdown"
    ),
    measure = factor(measure,
      levels = c(
        "Pharmacy First Service Total",
        "CP Consultation Service for minor illness (1577041000000109)",
        "Pharmacy First service (983341000000102)",
        "CP Pharmacy First Service (2129921000000100)"
      )
    ),
    data_desc = factor(data_desc,
      levels = c("total", "breakdown"),
      labels = c("Total", "Breakdown")
    )
  ) |>
  select(measure, interval_start, data_desc, value)

df_pf_consultations_breakdown <- df_pf_consultations %>% 
  filter(data_desc == "Breakdown")

df_pf_consultation_total <- df_pf_consultations %>% 
  filter(data_desc == "Total") %>% 
  distinct() %>% 
  select(-measure)

plot_pf_consultations <- df_pf_consultations_breakdown |>
  ggplot(
    aes(
      x = interval_start,
      y = value,
      colour = measure,
      shape = measure,
      fill = measure
    )
  ) +
  geom_point(size = 2.5) +
  geom_line(alpha = .2) +
  scale_x_date(
    date_breaks = "1 month",
    labels = scales::label_date_short()
  ) +
  guides(
    color = guide_legend(nrow = 2),
    shape = guide_legend(nrow = 2)
  ) +
  labs(
    title = NULL,
    x = NULL,
    y = NULL,
    colour = NULL,
    shape = NULL,
    fill = NULL
  ) +
  theme(
    legend.position = "bottom",
    text = element_text(size = 12),
    panel.background = element_blank(),
    axis.line = element_line(colour = "grey50"),
  ) +
  scale_colour_viridis_d(option = "plasma", end = .75) +
  scale_y_continuous(
    limits = c(0, 40000),
    labels = scales::label_number(),
    breaks = c(0, 10000, 20000, 30000, 40000)
  )

plot_pf_consultations

ggsave(
  filename = here("released_output", "results", "manuscript", "fig1_pf_consultation_count_total.png"),
  plot_pf_consultations,
  height = 3.5,
  width = 8
)
```

### Results for Figure 1 description

```{r, message=FALSE, warning=FALSE}
df_results_pf_total_counts <- df_measures %>%
  filter(measure_desc == "clinical_service") %>%
  filter(is.na(group_by)) |>
  group_by(interval_start) |>
  mutate(
    pf_consultation_total = sum(numerator, na.rm = TRUE),
    data_desc = "Pharmacy First Consultation"
  ) %>%
  select(interval_start, pf_consultation_total) %>%
  distinct() %>%
  ungroup() %>%
  mutate(pf_consultation_diff = pf_consultation_total - lag(pf_consultation_total)) %>%
  filter(interval_start >= "2024-02-01")

# Sum of consultations from feb to dec 2024
sum(df_results_pf_total_counts$pf_consultation_total)

df_results_pf_total_counts %>%
  filter(interval_start %in% c("2024-02-01", "2024-12-01", "2024-08-01", "2024-09-01", "2024-10-01"))
```

## OpenSAFELY Linkage

### Figure 2

```{r, message=FALSE, warning=FALSE, echo = FALSE, fig.height = 4, fig.width = 8}
# Create figure to show & of PF Med, Condition and both with linked PF consultations

df_pf_descriptive_stats <- df_descriptive_stats %>%
  filter(measure %in% c("pfmed_with_pfid", "pfcondition_with_pfid", "pfmed_and_pfcondition_with_pfid")) %>%
  mutate(
    measure = factor(measure,
      levels = c(
        "pfmed_with_pfid",
        "pfcondition_with_pfid",
        "pfmed_and_pfcondition_with_pfid"
      ),
      labels = c(
        "Medication",
        "Clinical condition",
        "Both"
      )
    )
  ) 
  
  df_pf_descriptive_stats <- df_pf_descriptive_stats %>%
  left_join(df_pf_consultation_total,
    by = c("interval_start")
  )

df_pf_descriptive_stats <- df_pf_descriptive_stats %>%
  filter(between(interval_start, as.Date("2024-02-01"), as.Date("2025-02-01"))) %>%
  group_by(interval_start) %>%
  mutate(measure = factor(measure, levels = c("Both", "Clinical condition", "Medication"))) |>
  arrange(desc(measure), .by_group = TRUE) |>
  mutate(
    ratio_exclusive = numerator / value,
    cumulative_ratio_exclusive = case_when(interval_start == max(df_pf_descriptive_stats$interval_start) ~ cumsum(ratio_exclusive), TRUE ~ NA)
  )

fig_pf_med_condition_linkage <- df_pf_descriptive_stats |>
  ggplot(
    aes(
      x = interval_start,
      y = ratio_exclusive,
      fill = measure
    )
  ) +
  geom_area(
    alpha = 0.85,
    linewidth = .5,
    colour = "white"
  ) +
  geom_label(
    aes(
      y = cumulative_ratio_exclusive,
      label = ifelse(is.na(ratio_exclusive), "", scales::percent(ratio_exclusive, accuracy = .1)),
    ),
    vjust = -0.05,
    size = 3.5,
    show.legend = FALSE,
    color = "black",
    fill = "white"
  ) +
  scale_fill_viridis_d() +
  guides(fill = guide_legend(reverse = TRUE)) +
  scale_y_continuous(
    limits = c(0, .5),
    labels = scales::percent
  ) +
  labs(
    x = NULL,
    y = NULL,
    fill = "Pharmacy First consultations linked to: "
  ) +
  scale_x_date(
    date_breaks = "1 month",
    labels = scales::label_date_short()
  ) +
  theme(
    panel.background = element_blank(),
    axis.line = element_line(colour = "grey50"),
    legend.position = "bottom",
    text = element_text(size = 14)
  )

fig_pf_med_condition_linkage

ggsave(
  filename = here("released_output", "results", "manuscript", "fig2_pf_med_condition.png"),
  fig_pf_med_condition_linkage,
  height = 4,
  width = 8
)
```

### Results for Figure 2 description

```{r}
df_results_pf_linkage <- df_pf_descriptive_stats %>%
  select(measure, interval_start, ratio, numerator) %>%
  group_by(interval_start) %>%
  mutate(
    ratio_total_linked = sum(ratio),
    ratio_total_unlinked = 1 - sum(ratio)
  ) %>%
  mutate(
    ratio_linked = percent(ratio, accuracy = 0.1),
    ratio_total_linked = percent(ratio_total_linked, accuracy = 0.1),
    ratio_total_unlinked = percent(ratio_total_unlinked, accuracy = 0.1),
  )

df_results_pf_linkage %>%
  filter(interval_start %in% c("2024-02-01", "2024-12-01", "2024-08-01", "2024-09-01", "2024-10-01"))

linkage_feb_to_dec <- df_results_pf_linkage %>%
  group_by(interval_start) %>%
  summarise(sum_ratio = sum(ratio)) %>%
  mutate(
    linkage_diff = sum_ratio - lag(sum_ratio),
    pct_diff = percent(linkage_diff, accuracy = 0.1)
  )
```

## Data comparison

### Figure 3

```{r, message=FALSE, warning=FALSE, echo = FALSE}
# Ideally I would like to load this at the top of this script
# But this file uses datasets created further down so it easiest to load it here
source(here("lib", "functions", "combine_os_nhsbsa_validation_data.R"))

# Pharmacy First Consultations
# Instead of only using the count of PF consultations in OS with a clinical
# condition we are using all PF consultations with a consultation id
df_pf_consultation_validatio_plot <- pf_validation |>
  filter(
    (data_source == "opensafely" &
      data_desc == "pf_consultation" &
      count_desc == "consultation_id") |
      (data_source == "nhs_bsa" &
        data_desc == "pf_consultation" &
        count_desc == "consultation_type")
  )

# Pivot wider to calculate ratio
df_pf_consultation_validatio_plot <- df_pf_consultation_validatio_plot |>
  select(date, data_source, count_method, count_total) |>
  pivot_wider(names_from = c(data_source, count_method), values_from = count_total) |>
  mutate(ratio = opensafely_opensafely_tpp / nhs_bsa_count_100pct)

# Select colours for groups
# Group 1: #CF4446FF
colour_group_1 <- paletteer_c("viridis::inferno", n = 10)[6]
# Group 1: #1B0C42FF
colour_group_2 <- paletteer_c("viridis::inferno", n = 10)[2]

vline_dates <- c(
  as.Date("2024-03-01"),
  as.Date("2024-05-01"),
  as.Date("2024-08-01"),
  as.Date("2024-09-01"),
  as.Date("2025-01-01")
)

get_mid_dates <- function(dates) {
  dates <- sort(as_date(dates))
  as_date(map2_dbl(dates[-length(dates)], dates[-1], ~ (as.numeric(.x) + as.numeric(.y)) / 2))
}

vline_label_xintercept <- get_mid_dates(c(as.Date("2024-02-01"), vline_dates))

vline_labels <- c(
  "Threshold: 1",
  "Threshold: 5",
  "Threshold: 10",
  "Threshold: 15",
  "Threshold: 20"
)

y_max <- max(
  df_pf_consultation_validatio_plot$nhs_bsa_count_100pct,
  df_pf_consultation_validatio_plot$opensafely_opensafely_tpp, na.rm = TRUE
)
# Create consultation validation plot
pf_validatio_consultation_plot <- df_pf_consultation_validatio_plot |>
  ggplot(aes(x = date)) +
  geom_vline(
    xintercept = vline_dates,
    linetype = "dotted",
    colour = "gray70",
    size = 0.3
  ) +
  annotate(
    "text",
    x = vline_label_xintercept,
    y = rep(y_max * 1.05, length(vline_dates)),  # adjust multiplier as needed
    label = vline_labels,
    angle = 0,
    size = 2,
    hjust = 0.5,
    vjust = 0
  ) +
  geom_point(
    aes(
      y = nhs_bsa_count_100pct,
      colour = "NHS BSA",
      shape = "NHS BSA"
    ),
    size = 2.6
  ) +
  geom_line(
    aes(y = nhs_bsa_count_100pct, colour = "NHS BSA"),
    alpha = .3,
    size = .5
  ) +
  geom_point(
    aes(
      y = opensafely_opensafely_tpp,
      colour = "OpenSAFELY-TPP",
      shape = "OpenSAFELY-TPP"
    ),
    size = 2.6
  ) +
  geom_line(
    aes(
      y = opensafely_opensafely_tpp,
      colour = "OpenSAFELY-TPP"
    ),
    alpha = .3,
    size = .5
  ) +
  geom_label(
    aes(
      y = opensafely_opensafely_tpp,
      label = scales::percent(ratio, accuracy = .1)
    ),
    colour = colour_group_2,
    vjust = -.5,
    size = 3.5
  ) +
  scale_y_continuous(
    limits = c(0, NA),
    labels = scales::label_number(),
    breaks = c(0, 50000, 100000, 150000, 200000, 250000)
  ) +
  scale_x_date(
    date_breaks = "1 month",
    labels = scales::label_date_short()
  ) +
  scale_colour_manual(
    values = c(
      "NHS BSA" = colour_group_1,
      "OpenSAFELY-TPP" = colour_group_2
    ),
    name = NULL
  ) +
  scale_shape_manual(
    values = c(
      "NHS BSA" = 15,
      "OpenSAFELY-TPP" = 16
    ),
    name = NULL
  ) +
  labs(
    x = NULL,
    y = NULL,
    colour = NULL,
    shape = NULL
  ) +
  theme(
    panel.background = element_blank(),
    axis.line = element_line(colour = "grey50"),
    legend.position = "bottom",
    text = element_text(size = 14)
  )

pf_validatio_consultation_plot

ggsave(
  filename = here("released_output", "results", "manuscript", "fig3_pf_os_nhsbsa_comparison.png"),
  pf_validatio_consultation_plot,
  height = 4,
  width = 8
)
```
# Appendix

## Data comparison adjusted for % linkage

### Consultation

```{r, message=FALSE, warning=FALSE, echo = FALSE}
# Pharmacy First Consultations
# Instead of only using the count of PF consultations in OS with a clinical
# condition we are using all PF consultations with a consultation id
df_pf_consultation_validation_plot <- pf_validation |>
  filter(
    (data_source == "opensafely" &
      data_desc == "pf_consultation" &
      count_desc == "consultation_type") |
      (data_source == "nhs_bsa" &
        data_desc == "pf_consultation" &
        count_desc == "consultation_type")
  )

# Pivot wider to calculate ratio
df_pf_consultation_validation_plot <- df_pf_consultation_validation_plot |>
  select(date, data_source, count_method, count_total) |>
  pivot_wider(names_from = c(data_source, count_method), values_from = count_total) |>
  mutate(ratio = opensafely_opensafely_tpp / nhs_bsa_count_100pct)

join_ratio <- df_pf_descriptive_stats |>
  select(date = interval_start, measure, ratio) |>
  filter(measure %in% c("Clinical condition", "Both")) |>
  group_by(date) |>
  mutate(ratio_consultation_type_in_os = sum(ratio, na.rm = TRUE)) |>
  ungroup() |>
  select(date, ratio_consultation_type_in_os)

df_pf_consultation_validation_adjusted_plot <- df_pf_consultation_validation_plot |>
  left_join(join_ratio) |>
  mutate(
    os_tpp_adjusted = round((opensafely_opensafely_tpp / (ratio_consultation_type_in_os * 100)) * 100, 0),
    ratio_adjusted = os_tpp_adjusted / nhs_bsa_count_100pct
  )

# Select colours for groups
# Group 1: #CF4446FF
colour_group_1 <- paletteer_c("viridis::inferno", n = 10)[6]
# Group 1: #1B0C42FF
colour_group_2 <- paletteer_c("viridis::inferno", n = 10)[2]
# Group 1: #781C6DFF
colour_group_3 <- paletteer_c("viridis::inferno", n = 10)[4]

# Create consultation validation plot
pf_validation_consultation_adjusted_plot <- df_pf_consultation_validation_adjusted_plot |>
  ggplot(aes(x = date)) +
  geom_point(
    aes(
      y = nhs_bsa_count_100pct,
      colour = "NHS BSA",
      shape = "NHS BSA"
    ),
    size = 2.6
  ) +
  geom_line(
    aes(y = nhs_bsa_count_100pct, colour = "NHS BSA"),
    alpha = .3,
    size = .5
  ) +
  geom_point(
    aes(
      y = opensafely_opensafely_tpp,
      colour = "OpenSAFELY-TPP",
      shape = "OpenSAFELY-TPP"
    ),
    size = 2.6
  ) +
  geom_line(
    aes(
      y = opensafely_opensafely_tpp,
      colour = "OpenSAFELY-TPP"
    ),
    alpha = .3,
    size = .5
  ) +
  geom_label(
    aes(
      y = opensafely_opensafely_tpp,
      label = scales::percent(ratio, accuracy = .1),
    ),
    colour = colour_group_2,
    vjust = -.5,
    size = 3.5
  ) +
  geom_point(
    aes(
      y = os_tpp_adjusted,
      colour = "OpenSAFELY-TPP (Adjusted)",
      shape = "OpenSAFELY-TPP (Adjusted)"
    ),
    size = 2.6
  ) +
  geom_line(
    aes(
      y = os_tpp_adjusted,
      colour = "OpenSAFELY-TPP (Adjusted)"
    ),
    alpha = .3,
    size = .5
  ) +
  geom_label(
    aes(
      y = os_tpp_adjusted,
      label = scales::percent(ratio_adjusted, accuracy = .1),
    ),
    colour = colour_group_3,
    vjust = -.5,
    size = 3.5
  ) +
  scale_y_continuous(labels = scales::number) +
  scale_x_date(
    date_breaks = "1 month",
    labels = scales::label_date_short()
  ) +
  scale_colour_manual(
    values = c(
      "NHS BSA" = colour_group_1,
      "OpenSAFELY-TPP" = colour_group_2,
      "OpenSAFELY-TPP (Adjusted)" = colour_group_3
    ),
    name = NULL
  ) +
  scale_shape_manual(
    values = c(
      "NHS BSA" = 15,
      "OpenSAFELY-TPP" = 16,
      "OpenSAFELY-TPP (Adjusted)" = 17
    ),
    name = NULL
  ) +
  labs(
    x = NULL,
    y = NULL,
    colour = NULL,
    shape = NULL
  ) +
  theme(
    panel.background = element_blank(),
    axis.line = element_line(colour = "grey50"),
    legend.position = "bottom",
    text = element_text(size = 14)
  ) +
  ggtitle("A. Pharmacy First Consultations")
```

### Medications

```{r, message=FALSE, warning=FALSE, echo = FALSE}
df_pf_medication_validation <- pf_validation |>
  filter(
    (data_source == "opensafely" &
      data_desc == "pf_medication" &
      count_desc == "dmd_code") |
      (data_source == "nhs_bsa" &
        data_desc == "pf_medication" &
        count_desc == "bnf_paragraph")
  )

df_pf_medication_validation_plot <- df_pf_medication_validation |>
  select(date, data_source, count_method, count_total) |>
  pivot_wider(names_from = c(data_source, count_method), values_from = count_total) |>
  mutate(ratio = opensafely_opensafely_tpp / nhs_bsa_count_100pct)

linked_ratio <- df_pf_descriptive_stats |>
  select(date = interval_start, measure, ratio) |>
  filter(measure %in% c("Medication", "Both")) |>
  group_by(date) |>
  mutate(ratio_medication_in_os = sum(ratio, na.rm = TRUE)) |>
  ungroup() |>
  select(date, ratio_medication_in_os)


df_pf_medication_validation_adjusted_plot <- df_pf_medication_validation_plot |>
  left_join(linked_ratio) |>
  mutate(
    os_tpp_adjusted = round((opensafely_opensafely_tpp / (ratio_medication_in_os * 100)) * 100, 0),
    ratio_adjusted = os_tpp_adjusted / nhs_bsa_count_100pct
  )

# Create consultation validation plot
pf_medication_validation_adjusted_plot <- df_pf_medication_validation_adjusted_plot |>
  ggplot(aes(x = date)) +
  geom_point(
    aes(
      y = nhs_bsa_count_100pct,
      colour = "NHS BSA",
      shape = "NHS BSA"
    ),
    size = 2.6
  ) +
  geom_line(
    aes(y = nhs_bsa_count_100pct, colour = "NHS BSA"),
    alpha = .3,
    size = .5
  ) +
  geom_point(
    aes(
      y = opensafely_opensafely_tpp,
      colour = "OpenSAFELY-TPP",
      shape = "OpenSAFELY-TPP"
    ),
    size = 2.6
  ) +
  geom_line(
    aes(
      y = opensafely_opensafely_tpp,
      colour = "OpenSAFELY-TPP"
    ),
    alpha = .3,
    size = .5
  ) +
  geom_label(
    aes(
      y = opensafely_opensafely_tpp,
      label = scales::percent(ratio, accuracy = .1),
    ),
    colour = colour_group_2,
    vjust = -.5,
    size = 3.5
  ) +
  geom_point(
    aes(
      y = os_tpp_adjusted,
      colour = "OpenSAFELY-TPP (Adjusted)",
      shape = "OpenSAFELY-TPP (Adjusted)"
    ),
    size = 2.6
  ) +
  geom_line(
    aes(
      y = os_tpp_adjusted,
      colour = "OpenSAFELY-TPP (Adjusted)"
    ),
    alpha = .3,
    size = .5
  ) +
  geom_label(
    aes(
      y = os_tpp_adjusted,
      label = scales::percent(ratio_adjusted, accuracy = .1),
    ),
    colour = colour_group_3,
    vjust = -.5,
    size = 3.5
  ) +
  scale_y_continuous(labels = scales::number) +
  scale_x_date(
    date_breaks = "1 month",
    labels = scales::label_date_short()
  ) +
  scale_colour_manual(
    values = c(
      "NHS BSA" = colour_group_1,
      "OpenSAFELY-TPP" = colour_group_2,
      "OpenSAFELY-TPP (Adjusted)" = colour_group_3
    ),
    name = NULL
  ) +
  scale_shape_manual(
    values = c(
      "NHS BSA" = 15,
      "OpenSAFELY-TPP" = 16,
      "OpenSAFELY-TPP (Adjusted)" = 17
    ),
    name = NULL
  ) +
  labs(
    x = NULL,
    y = NULL,
    colour = NULL,
    shape = NULL
  ) +
  theme(
    panel.background = element_blank(),
    axis.line = element_line(colour = "grey50"),
    legend.position = "bottom",
    text = element_text(size = 14)
  ) +
  ggtitle("B. Pharmacy First Medications")
```

```{r fig.height = 8, fig.width=10}
# Combine plots
validation_combined_adjusted_plot <- pf_validation_consultation_adjusted_plot / pf_medication_validation_adjusted_plot + plot_layout(guides = "collect") & theme(legend.position = "bottom")

validation_combined_adjusted_plot

ggsave(
  filename = here("released_output", "results", "manuscript", "figX_pf_os_nhsbsa_adjusted_comparison.png"),
  validation_combined_adjusted_plot,
  height = 8,
  width = 10
)
```
