---
title: "Pharmacy First"
output:
  html_document:
    toc: true
    toc_depth: 4
  pdf_document: default
date: "`r format(Sys.time(), '%d %B, %Y')`"
bibliography: references.bib
link-citations: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(here)
library(readr)
library(gt)
library(patchwork)
```

```{r load-data, message=FALSE, warning=FALSE}
# Load functions
source(here("lib", "functions", "tidy_measures.R"))
source(here("lib", "functions", "plot_measures.R"))

# Load validation data:
# - df_bsa_medication_validation: date, pharmacy_advanced_service, bnf_paragraph, count
# - df_bsa_consultation_validation: date, consultation_type, source, count_method, count
source(here("lib", "functions", "load_validation_data.R"))

# Load opensafely ouputs:
# - df_measures: measure, interval_start, interval_end, ratio numerator, denominator, age_band, sex,imd, region, ethnicity
# - df_descriptive_stats: measure, interval_start, interval_end, ratio numerator, denominator
# - df_pfmed: measure, interval_start, interval_end, ratio, numerator, denominator, dmd_code
# - df_condition_provider: measure, interval_start, interval_end, ratio, numerator, denominator, pf_status, imd
source(here("lib", "functions", "load_opensafely_outputs.R"))
```

```{r, message=FALSE, warning=FALSE}

# Create figure for total count of Pharmacy First consultations for each code (3 codes)
df_measures_selected <- df_measures %>%
  filter(measure_desc == "clinical_service") %>%
  filter(is.na(group_by)) |>
  select(measure, interval_start, numerator) |>
  mutate(measure = factor(measure,
    levels = c("Consultation Service", "Pharmacy First Consultation"),
    labels = c(
      "Consultation Service for minor illness (1577041000000109)",
      "Pharmacy First service (983341000000102)"
    )
  ))

plot_measures(
  df_measures_selected,
  select_value = numerator,
  select_interval_date = interval_start,
  legend_position = "bottom",
  facet_wrap = FALSE,
  facet_var = measure,
  y_label = "Total Count",
  colour_var = measure,
  guide_nrow = 1,
  save_path = "fig_pf_individual_consultations_count.png"
) 

# Create figure for total count of Pharmacy First Consultations (GROUPED)
df_measures_selected <- df_measures_selected |>
  group_by(interval_start) |>
  mutate(
    pf_consultation_total = sum(numerator, na.rm = TRUE),
    data_desc = "Pharmacy First Consultation"
  ) 

plot_measures(
  df_measures_selected,
  select_value = pf_consultation_total,
  select_interval_date = interval_start,
  legend_position = "bottom",
  facet_wrap = FALSE,
  facet_var = data_desc,
  y_label = "Total Count",
  colour_var = data_desc,
  guide_nrow = 1,
  save_path = "fig_pf_grouped_consultations_count.png",
)

```

```{r, message=FALSE, warning=FALSE, fig.height=10, fig.width=8}
# Create figure for total count of Pharmacy First grouped conditions (no breakdowns)
df_measures_selected <- df_measures %>%
  filter(measure_desc == "clinical_condition") %>%
  filter(is.na(group_by))

# Create visualisation
plot_measures(
  df_measures_selected,
  select_value = numerator,
  select_interval_date = interval_end,
  guide_nrow = 1,
  facet_wrap = TRUE,
  facet_var = measure,
  title = "Pharmacy First Conditions",
  y_label = "Number of codes for PF conditions",
  save_path = "fig_pf_grouped_conditions_count.png"
)
```

### Breakdown by age

```{r, message=FALSE, warning=FALSE, fig.height=4, fig.width=8}
# Create figure for total count of PF consultations by age
df_measures_selected <- df_measures %>%
  filter(measure_desc == "pharmacy_first_services") %>%
  filter(group_by == "Age band")

# Create visualisation
plot_measures(
  df_measures_selected,
  select_value = numerator,
  select_interval_date = interval_end,
  colour_var = age_band,
  guide_nrow = 1,
  facet_wrap = TRUE,
  facet_var = measure,
  title = "Pharmacy First Consultations",
  y_label = "Number of codes for PF consultations",
  save_path = "fig_pf_consultations_by_age_count.png",
  colour_palette = gradient_palette
)

# Create figure for rate of PF consultations by age
df_measures_selected <- df_measures %>%
  filter(measure_desc == "pharmacy_first_services") %>%
  filter(group_by == "Age band")

# Create visualisation
plot_measures(
  df_measures_selected,
  select_value = ratio,
  select_interval_date = interval_end,
  colour_var = age_band,
  guide_nrow = 1,
  facet_wrap = TRUE,
  facet_var = measure,
  scale_measure = "rate",
  title = "Rate of Pharmacy First Consultations per 1000 people",
  y_label = "Number of codes for FP consultations",
  save_path = "fig_pf_consultations_by_age_rate.png",
  colour_palette = gradient_palette
)
```

```{r, message=FALSE, warning=FALSE, fig.height=8, fig.width=8}
# Create figure for total count of PF clinical conditions broken down by age
df_measures_selected <- df_measures %>%
  filter(measure_desc == "clinical_condition") %>%
  filter(group_by == "Age band")

# Create visualisation
plot_measures(
  df_measures_selected,
  select_value = numerator,
  select_interval_date = interval_end,
  colour_var = age_band,
  guide_nrow = 1,
  facet_wrap = TRUE,
  facet_var = measure,
  title = "Pharmacy First Conditions",
  y_label = "Number of codes for PF conditions",
  save_path = "fig_pf_conditions_by_age_count.png",
  colour_palette = gradient_palette
)

# Create figure for rate of PF clinical conditions broken down by age
df_measures_selected <- df_measures %>%
  filter(measure_desc == "clinical_condition") %>%
  filter(group_by == "Age band")

# Create visualisation
plot_measures(
  df_measures_selected,
  select_value = ratio,
  select_interval_date = interval_end,
  colour_var = age_band,
  guide_nrow = 1,
  facet_wrap = TRUE,
  facet_var = measure,
  scale_measure = "rate",
  title = "Rate of Pharmacy First Conditions per 1000 people",
  y_label = "Number of codes for PF conditions",
  save_path = "fig_pf_conditions_by_age_rate.png",
  colour_palette = gradient_palette
)
```

### Breakdown by sex

```{r, message=FALSE, warning=FALSE, fig.height=4, fig.width=8}
# Create figure for total count of PF consultations broken down by sex
df_measures_selected <- df_measures %>%
  filter(measure_desc == "pharmacy_first_services") %>%
  filter(group_by == "Sex")

# Create visualisation
plot_measures(
  df_measures_selected,
  select_value = numerator,
  select_interval_date = interval_end,
  colour_var = sex,
  guide_nrow = 1,
  facet_wrap = TRUE,
  facet_var = measure,
  title = "Pharmacy First Consultations",
  y_label = "Number of codes for FP consultations",
  save_path = "fig_pf_consultations_by_sex_count.png",
  colour_palette = sex_palette
)

# Create figure for rate of PF consultations broken down by sex
df_measures_selected <- df_measures %>%
  filter(measure_desc == "pharmacy_first_services") %>%
  filter(group_by == "Sex")

# Create visualisation
plot_measures(
  df_measures_selected,
  select_value = ratio,
  select_interval_date = interval_end,
  colour_var = sex,
  guide_nrow = 1,
  facet_wrap = TRUE,
  facet_var = measure,
  scale_measure = "rate",
  title = "Rate of Pharmacy First Consultations per 1000 people",
  y_label = "Number of codes for FP consultations",
  save_path = "fig_pf_consultations_by_sex_rate.png",
  colour_palette = sex_palette
)

```

```{r, message=FALSE, warning=FALSE, fig.height=8, fig.width=8}
# Create figure for total count of PF clinical conditions by sex
df_measures_selected <- df_measures %>%
  filter(measure_desc == "clinical_condition") %>%
  filter(group_by == "Sex")

# Create visualisation
plot_measures(
  df_measures_selected,
  select_value = numerator,
  select_interval_date = interval_end,
  colour_var = sex,
  guide_nrow = 1,
  facet_wrap = TRUE,
  facet_var = measure,
  title = "Pharmacy First Conditions",
  y_label = "Number of codes for PF conditions",
  save_path = "fig_pf_conditions_by_sex_count.png",
  colour_palette = sex_palette
)

# Create figure for rate of PF clinical conditions by sex
df_measures_selected <- df_measures %>%
  filter(measure_desc == "clinical_condition") %>%
  filter(group_by == "Sex")

# Create visualisation
plot_measures(
  df_measures_selected,
  select_value = ratio,
  select_interval_date = interval_end,
  colour_var = sex,
  guide_nrow = 1,
  facet_wrap = TRUE,
  facet_var = measure,
  scale_measure = "rate",
  title = "Rate of Pharmacy First Conditions per 1000 people",
  y_label = "Number of codes for PF conditions",
  save_path = "fig_pf_conditions_by_sex_rate.png"
) + scale_color_manual(values = sex_palette)
```

### Breakdown by IMD

```{r, message=FALSE, warning=FALSE, fig.height=4, fig.width=8}
# Create figure for total count of PF consultations by IMD
df_measures_selected <- df_measures %>%
  filter(measure_desc == "pharmacy_first_services") %>%
  filter(group_by == "IMD")

# Create visualisation
plot_measures(
  df_measures_selected,
  select_value = numerator,
  select_interval_date = interval_end,
  colour_var = imd,
  guide_nrow = 1,
  facet_wrap = TRUE,
  facet_var = measure,
  title = "Pharmacy First Consultations",
  y_label = "Number of codes for FP consultations",
  save_path = "fig_pf_consultations_by_imd_count.png",
  colour_palette = gradient_palette
)

# Create figure for rate of PF consultations by IMD
df_measures_selected <- df_measures %>%
  filter(measure_desc == "pharmacy_first_services") %>%
  filter(group_by == "IMD")

# Create visualisation
plot_measures(
  df_measures_selected,
  select_value = ratio,
  select_interval_date = interval_end,
  colour_var = imd,
  guide_nrow = 1,
  facet_wrap = TRUE,
  facet_var = measure,
  scale_measure = "rate",
  title = "Rate of Pharmacy First Consultations per 1000 people",
  y_label = "Number of codes for FP consultations",
  save_path = "fig_pf_consultations_by_imd_rate.png",
  colour_palette = gradient_palette
)
```

```{r, message=FALSE, warning=FALSE, fig.height=8, fig.width=8}
# Create figure for total count of PF clinical conditions by IMD
df_measures_selected <- df_measures %>%
  filter(measure_desc == "clinical_condition") %>%
  filter(group_by == "IMD")

# Create visualisation
plot_measures(
  df_measures_selected,
  select_value = numerator,
  select_interval_date = interval_end,
  colour_var = imd,
  guide_nrow = 1,
  facet_wrap = TRUE,
  facet_var = measure,
  title = "Pharmacy First Conditions",
  y_label = "Number of codes for PF conditions",
  save_path = "fig_pf_conditions_by_imd_count.png",
  colour_palette = gradient_palette
)

# Create figure for rate of PF clinical conditions by IMD
df_measures_selected <- df_measures %>%
  filter(measure_desc == "clinical_condition") %>%
  filter(group_by == "IMD")

# Create visualisation
plot_measures(
  df_measures_selected,
  select_value = ratio,
  select_interval_date = interval_end,
  colour_var = imd,
  guide_nrow = 1,
  facet_wrap = TRUE,
  facet_var = measure,
  scale_measure = "rate",
  title = "Rate of Pharmacy First Conditions per 1000 people",
  y_label = "Number of codes for PF conditions",
  save_path = "fig_pf_conditions_by_imd_rate.png",
  colour_palette = gradient_palette
)
```

### Breakdown by region

```{r, message=FALSE, warning=FALSE, fig.height=4, fig.width=8}
# Create figure for total count of PF consultations by region
df_measures_selected <- df_measures %>%
  filter(measure_desc == "pharmacy_first_services") %>%
  filter(group_by == "Region")

# Create visualisation
plot_measures(
  df_measures_selected,
  select_value = numerator,
  select_interval_date = interval_end,
  colour_var = region,
  guide_nrow = 2,
  facet_wrap = TRUE,
  facet_var = measure,
  title = "Pharmacy First Consultations",
  y_label = "Number of codes for FP consultations",
  save_path = "fig_pf_consultations_by_region_count.png",
  colour_palette = region_palette
)

# Create figure for rate of PF consultations by IMD
df_measures_selected <- df_measures %>%
  filter(measure_desc == "pharmacy_first_services") %>%
  filter(group_by == "Region")

# Create visualisation
plot_measures(
  df_measures_selected,
  select_value = ratio,
  select_interval_date = interval_end,
  colour_var = region,
  guide_nrow = 2,
  facet_wrap = TRUE,
  facet_var = measure,
  scale_measure = "rate",
  title = "Rate of Pharmacy First Consultations per 1000 people",
  y_label = "Number of codes for FP consultations",
  save_path = "fig_pf_consultations_by_region_rate.png",
  colour_palette = region_palette
)
```

```{r, message=FALSE, warning=FALSE, fig.height=8, fig.width=8}
# Create figure for total count of PF clinical conditions by region
df_measures_selected <- df_measures %>%
  filter(measure_desc == "clinical_condition") %>%
  filter(group_by == "Region")

# Create visualisation
plot_measures(
  df_measures_selected,
  select_value = numerator,
  select_interval_date = interval_end,
  colour_var = region,
  guide_nrow = 2,
  facet_wrap = TRUE,
  facet_var = measure,
  title = "Pharmacy First Conditions",
  y_label = "Number of codes for PF conditions",
  save_path = "fig_pf_conditions_by_region_count.png",
  colour_palette = region_palette
)

# Create figure for rate of PF clinical conditions by region
df_measures_selected <- df_measures %>%
  filter(measure_desc == "clinical_condition") %>%
  filter(group_by == "Region")

# Create visualisation
plot_measures(
  df_measures_selected,
  select_value = ratio,
  select_interval_date = interval_end,
  colour_var = region,
  guide_nrow = 2,
  facet_wrap = TRUE,
  facet_var = measure,
  scale_measure = "rate",
  title = "Rate of Pharmacy First Conditions per 1000 people",
  y_label = "Number of codes for PF conditions",
  save_path = "fig_pf_conditions_by_region_rate.png",
  colour_palette = region_palette
)
```

### Breakdown by ethnicity

```{r, message=FALSE, warning=FALSE, fig.height=4, fig.width=8}
# Create figure for total count of PF consultations by ethnicity
df_measures_selected <- df_measures %>%
  filter(measure_desc == "pharmacy_first_services") %>%
  filter(group_by == "Ethnicity")

# Create visualisation
plot_measures(
  df_measures_selected,
  select_value = numerator,
  select_interval_date = interval_end,
  colour_var = ethnicity,
  guide_nrow = 2,
  facet_wrap = TRUE,
  facet_var = measure,
  title = "Pharmacy First Consultations",
  y_label = "Number of codes for FP consultations",
  save_path = "fig_pf_consultations_by_ethnicity_count.png",
  colour_palette = ethnicity_palette
)

# Create figure for rate of PF consultations by ethnicity
df_measures_selected <- df_measures %>%
  filter(measure_desc == "pharmacy_first_services") %>%
  filter(group_by == "Ethnicity")

# Create visualisation
plot_measures(
  df_measures_selected,
  select_value = ratio,
  select_interval_date = interval_end,
  colour_var = ethnicity,
  guide_nrow = 2,
  facet_wrap = TRUE,
  facet_var = measure,
  scale_measure = "rate",
  title = "Rate of Pharmacy First Consultations per 1000 people",
  y_label = "Number of codes for FP consultations",
  save_path = "fig_pf_consultations_by_ethnicity_rate.png",
  colour_palette = ethnicity_palette
)
```

```{r, message=FALSE, warning=FALSE, fig.height=8, fig.width=8}
# Create figure for total count of PF clinical conditions by ethnicity
df_measures_selected <- df_measures %>%
  filter(measure_desc == "clinical_condition") %>%
  filter(group_by == "Ethnicity")

# Create visualisation
plot_measures(
  df_measures_selected,
  select_value = numerator,
  select_interval_date = interval_end,
  colour_var = ethnicity,
  guide_nrow = 2,
  facet_wrap = TRUE,
  facet_var = measure,
  title = "Pharmacy First Conditions",
  y_label = "Number of codes for PF conditions",
  save_path = "fig_pf_conditions_by_ethnicity_count.png",
  colour_palette = ethnicity_palette
)

# Create figure for rate of PF clinical conditions by ethnicity
df_measures_selected <- df_measures %>%
  filter(measure_desc == "clinical_condition") %>%
  filter(group_by == "Ethnicity")

# Create visualisation
plot_measures(
  df_measures_selected,
  select_value = ratio,
  select_interval_date = interval_end,
  colour_var = ethnicity,
  guide_nrow = 2,
  facet_wrap = TRUE,
  facet_var = measure,
  scale_measure = "rate",
  title = "Rate of Pharmacy First Conditions per 1000 people",
  y_label = "Number of codes for PF conditions",
  save_path = "fig_pf_conditions_by_ethnicity_rate.png",
  colour_palette = ethnicity_palette
)
```
```{r, message=FALSE, warning=FALSE, echo = FALSE}
# Create figure to compare OS and BSA counts for PF clinical conditions

# OpenSAFELY data for clinical conditions into a tidy df
df_opensafely_validation <- df_measures %>%
  filter(measure_desc == "clinical_condition") %>%
  # filter(interval_start >= as.Date("2024-02-01") & interval_start <= as.Date("2024-07-30")) %>%
  filter(is.na(group_by)) %>%
  select(date = interval_start, consultation_type = measure, count = numerator) %>%
  mutate(
    source = "opensafely",
    count_method = "opensafely_tpp"
  ) |>
  filter(date >= "2024-01-01") %>%
  relocate(date, consultation_type, source, count_method, count)

# Combining rows from OS and BSA validation dataframes
df_validation_condition <- bind_rows(df_opensafely_validation, df_bsa_consultation_validation)

# Line graph comparing clinical condition counts of BSA and OS data
df_validation_condition_counts <- df_validation_condition %>%
  filter(count_method %in% c("opensafely_tpp", "count_40pct")) %>%
  filter(date >= "2024-01-01") %>%
  mutate(source = factor(source,
    levels = c("opensafely", "nhs_bsa"),
    labels = c("OpenSAFELY-TPP", "NHS BSA (40%)")
  ))

# Create visualisation
fig_validation_condition_count <- plot_measures(
  df_validation_condition_counts,
  select_value = count,
  select_interval_date = date,
  colour_var = consultation_type,
  guide_nrow = 2,
  facet_wrap = TRUE,
  facet_var = source,
  y_label = "Count",
  save_path = "fig_validation_conditions.png",
  y_scale = "free_y",
  shapes = "condition_shapes",
  colour_palette = "plasma",
  date_breaks = "2 month"
)

# Another plot visualising the percentage
df_validation_condition_pct <- df_validation_condition %>%
  filter(count_method %in% c("opensafely_tpp", "count_40pct")) %>%
  filter(date >= "2024-01-01") %>%
  pivot_wider(names_from = c(source, count_method), values_from = count) %>%
  mutate(source = "Percentage of NHS BSA (40%) in OpenSAFELY")

fig_validation_condition_pct <- plot_measures(
  df_validation_condition_pct,
  select_value = opensafely_opensafely_tpp / nhs_bsa_count_40pct,
  select_interval_date = date,
  colour_var = consultation_type,
  guide_nrow = 2,
  facet_wrap = TRUE,
  facet_var = source,
  scale_measure = "percent",
  y_label = "Percent",
  save_path = "fig_validation_conditions_pct.png",
  y_scale = "free_y",
  shapes = "condition_shapes",
  colour_palette = "plasma",
  date_breaks = "2 month"
)

# Combining the plots with patchwork function
patch_figures(
  fig_validation_condition_count,
  fig_validation_condition_pct,
  "fig_validation_condition_count_pct.png"
  )

```

```{r, message=FALSE, warning=FALSE, echo = FALSE, fig.width=8}
# Create figure to show & of PF Med, Condition and both with linked PF consultations

df_descriptive_stats <- df_descriptive_stats %>%
  mutate(
    measure = factor(measure,
      levels = c("pf_with_pfmed", "pf_with_pfcondition", "pf_with_pfmed_and_pfcondition"),
      labels = c("PF Med", "PF Condition", "PF Med & PF Condition")
    )
  ) 

plot_measures(
  df_descriptive_stats,
  select_value = ratio,
  select_interval_date = interval_start,
  colour_var = measure,
  guide_nrow = 2,
  facet_wrap = FALSE,
  facet_var = measure,
  scale_measure = "percent",
  y_label = "Percent",
  save_path = "fig_pf_descriptive_stats.png",
  colour_palette = dark2_palette,
  date_breaks = "1 month"
)

```

```{r, message=FALSE, warning=FALSE, echo = FALSE}
# Create figure to compare OS and BSA counts for PF medication

df_bsa_medication_validation_sum <- df_bsa_medication_validation %>%
  group_by(date) %>%
  summarise(count = sum(count) * 0.4) %>%
  mutate(
    source = "nhs_bsa",
    count_method = "count_40pct"
  )
range(df_pfmed$interval_start)
df_opensafely_pfmed_sum <- df_pfmed %>%
  rename(date = interval_start) %>%
  group_by(date) %>%
  summarise(count = sum(numerator)) %>%
  mutate(
    source = "opensafely_tpp",
    count_method = "opensafely_tpp"
  )

df_validation_med_counts <- bind_rows(df_opensafely_pfmed_sum, df_bsa_medication_validation_sum) |>
  filter(date >= "2024-01-01" & date <= "2024-07-01")

df_validation_med_counts <- df_validation_med_counts %>%
  mutate(
    source = factor(source, levels = c("opensafely_tpp", "nhs_bsa"), labels = c("OpenSAFELY-TPP", "NHS BSA")),
    count_method = factor(count_method, levels = c("opensafely_tpp", "count_40pct"), labels = c("OpenSAFELY-TPP", "NHS BSA (40%)"))
  ) 

fig_validation_med_count <- plot_measures(
  df_validation_med_counts,
  select_value = count,
  select_interval_date = date,
  colour_var = count_method,
  guide_nrow = 1,
  facet_wrap = TRUE,
  facet_var = source,
  y_scale = "free_y",
  y_label = "Count",
  save_path = "fig_validation_med_counts.png",
  colour_palette = "plasma",
  date_breaks = "1 month"
)

# Another plot visualising the percentage
df_validation_med_pct <- df_validation_med_counts %>%
  filter(count_method %in% c("OpenSAFELY-TPP", "NHS BSA (40%)")) %>%
  pivot_wider(names_from = c(source, count_method), values_from = count) %>%
  mutate(source = "Percentage of NHS BSA (40%) in OpenSAFELY") 

fig_validation_med_pct <- plot_measures(
  df_validation_med_pct,
  select_value = `OpenSAFELY-TPP_OpenSAFELY-TPP` / `NHS BSA_NHS BSA (40%)`,
  select_interval_date = date,
  colour_var = source,
  guide_nrow = 1,
  facet_wrap = TRUE,
  facet_var = source,
  scale_measure = "percent",
  y_scale = "free_y",
  y_label = "Count",
  save_path = "fig_validation_med_pct.png",
  colour_palette = "plasma",
  date_breaks = "1 month"
)

# Combining the plots with patchwork
patch_figures(fig_validation_med_count, fig_validation_med_pct, "fig_validation_medication_count_pct.png")

```
```{r, message=FALSE, warning=FALSE, echo = FALSE, fig.width=8}
# Create figure to compare clinical events linked to PF consultation and not linked

df_condition_provider_grouped <- df_condition_provider %>%
  group_by(measure, interval_start, pf_status) %>%
  summarise(
    count = sum(numerator)
  ) %>%
  mutate(
    measure = factor(measure,
      levels = c(
        "count_acute_sinusitis_total",
        "count_infected_insect_bite_total",
        "count_uncomplicated_urinary_tract_infection_total",
        "count_acute_otitis_media_total",
        "count_acute_pharyngitis_total",
        "count_herpes_zoster_total",
        "count_impetigo_total"
      ),
      labels = c(
        "Acute Sinusitis",
        "Infected Insect Bite",
        "UTI",
        "Acute Otitis Media",
        "Acute Pharyngitis",
        "Herpes Zoster",
        "Impetigo"
      )
    ),
    pf_status = factor(pf_status,
      levels = c(TRUE, FALSE),
      labels = c("Linked to Pharmacy First consultation", "Not linked to Pharmacy First consultation")
    )
  )

fig_validation_med_count <- plot_measures(
  df_condition_provider_grouped,
  select_value = count,
  select_interval_date = interval_start,
  colour_var = pf_status,
  guide_nrow = 1,
  facet_wrap = TRUE,
  facet_var = measure,
  y_label = "Count",
  save_path = "fig_pf_condition_provider_count.png",
  date_breaks = "6 month",
  colour_palette = "plasma"
)

```

# References
